### ISSUE TITLE
signatures made with encryption key.

### ISSUE THREAD

**Issue by stef** [dejavusecurity/OutlookPrivacyPlugin#100]
i test with an encryption subkey, when i sign a message, the encryption subkey is used instead of the signing master key. This leads to the following error:

gpg: encrypted with 4096-bit RSA key, ID 0xFFFFFFFFFFFFF, created 2015-09-07
      "user1 <user1@example.com>"
gpg: Signature made Mon 07 Sep 2015 01:47:33 PM CEST
gpg:                using RSA key 0xFFFFFFFFFFFFF
gpg: WARNING: signing subkey 0xFFFFFFFFFFFFFF is not cross-certified
gpg: please see https://gnupg.org/faq/subkey-cross-certify.html for more information
gpg: Can't check signature: general error

an encrypting subkey should not be used for signing, instead the master signing key should be used for this.

This messes up all signatures that my peers want to verify, and i cannot cross-certify the signing key, because it's not a signing key. if i do as suggested by the gpg warning message, gpg rightly refuses to cross-certify with the following message:

subkey FFFFFFF does not sign and so does not need to be cross-certified.

thanks for fixing this.
s

**Comment by YHSC** [comment]
Same here. it is using the encrypt key for signing...

It would' have to check which key is for signing, which aint hard.

Would be happy about a quick fix.

**Comment by Meddington** [comment]
What version of the plugin are you using?

**Comment by stef** [comment]
beta 49

**Comment by YHSC** [comment]
beta 49 too

**Comment by Meddington** [comment]
Please give beta 50 a shot. I fixed an issue with key selection for signing.

**Comment by evolvia31** [comment]
beta51 remove the problem to me.
