### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by adituv** [dejavusecurity/OutlookPrivacyPlugin#101]
I tried to send a signed message with attachment.  All columns are less than or equal to 68 characters wide, so I'm surprised to see a "long lines" warning dialog.  I choose the "sign anyway" option and I get the attached error.

![image](https://cloud.githubusercontent.com/assets/1254246/9848531/e3377f68-5ad9-11e5-9c19-4d29db5ed444.png)

**Comment by 4Vs** [comment]
Reinstalling of the lastest version solved that issue for me.

Diese Nachricht wurde mobil versendet und ist daher recht kurz gehalten.

**Comment by adituv** [comment]
Huh, reinstalling did the trick.  I wonder what happened that made that necessary.  I'll shout if it happens again; thanks :)
