### ISSUE TITLE
Passphrase prompt doesn't handle umlauts

### ISSUE THREAD

**Issue by bkaestner** [dejavusecurity/OutlookPrivacyPlugin#102]
If a passphrase contains an umlaut (ä, ö, ü, Ü, Ä, Ö, ß, ...), the dialog won't accept the pass phrase and instead asks again.

**Comment by Meddington** [comment]
This appears to be true.  Deep in the Bouncy Castle crypto code they do a straight char -> byte conversion w/o taking into account unicode/multi-byte characters.

**Comment by Meddington** [comment]
I've added a patch to the next rev to treat all passwords as Unicode. Will be in next beta.
