### ISSUE TITLE
Resources are not installed (v1 BETA-49)

### ISSUE THREAD

**Issue by roodemol** [dejavusecurity/OutlookPrivacyPlugin#106]
Hello,

I've installed the latest plugin (v1 BETA-49) onto a new machine with Outlook 2010. When Outlook opens I'm getting this error message:
Downloading file:///C:/Program Files (x86)/Outlook Privacy Plugin/Resources/GpgLogo.png did not succeed.

The Resources folder is missing on the new machine.

Regards,
Gilles

**Comment by Meddington** [comment]
The resources are built into the binaries, no Resources folder needs to be installed.  I suggest uninstalling the plugin, rebooting, and try re-installing with all office applications closed.

**Comment by roodemol** [comment]
Hello,

I tried you suggestion, but it didn't solved the issue, here's what I did:
1. Logged in as administrator
2. Uninstalled the plugin
3. Rebooted my machine
4. Reinstalled it as administrator
5. Logged in as standard user
6. Started Outlook, with the same problem:

![outlookprivacypluginerror](https://cloud.githubusercontent.com/assets/1041652/10302127/b3838e24-6c09-11e5-9f24-2b730e049b65.PNG)

Could it be a problem with the user rights.

Regards,
Gilles

**Comment by roodemol** [comment]
Hello,
I think I've found the problem, I've two accounts on my machine:
* Administrator, with installation rights
* Gilles, my account for day to day work without instillation rights

I've installed the plugin as administrator, and that could be the problem because the following keys are only added to the administratior account in the registry but not to my work account:
[HKEY_CURRENT_USER\Software\Microsoft\Office\Outlook\Addins\OutlookPrivacyPlugin]
"Description"="Outlook Privacy Plugin is a security extension for Outlook. It enables Outlook to send and receive email messages that are encrypted and/or signed with the OpenPGP standard."
"FriendlyName"="Outlook Privacy Plugin"
"LoadBehavior"=dword:00000003
"Manifest"="file:///C:\\Program Files (x86)\\Outlook Privacy Plugin\\OutlookPrivacyPlugin.vsto|vstolocal"

Now the plugin also works after I have imported them manually while being logged in my work account.

Probably you have to add an option to install the plugin for all the users.

Regards,
Gilles
