### ISSUE TITLE
Error validating signed message with Enigmail and vice versa

### ISSUE THREAD

**Issue by evolvia31** [dejavusecurity/OutlookPrivacyPlugin#107]
Hi ,

I have a strange bug if i sign a mail from my Outlook and the recipient read with Thunderbird + Enigmail then Enigmail can't validate the message.
So i have also the problem in the other side, if i receive a mail whihch is signed by Enigmail, OutlookPrivacy plugin can't validate signature.

Is it a bug or have you a fix ?

I use the V1 Beta 49 version of outlookPrivacyPlugin with outlook 2010 64 Bits version on Windows 7

i have also Thunderbird with enigmail 1.8.2.

**Comment by YHSC** [comment]
One of it is probably because of this:
signatures made with encryption key. #100

**Comment by Meddington** [comment]
Please check beta 50 and see if it resolves this issue.

**Comment by Meddington** [comment]
closing as duplicate of 100.
