### ISSUE TITLE
Accessing MIME message body throws error

### ISSUE THREAD

**Issue by Chewie9999** [dejavusecurity/OutlookPrivacyPlugin#109]
---------------------------
Outlook Privacy Error
---------------------------
The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
---------------------------
OK   
---------------------------

Outlook version is 15.0.4753.1002 and is connected to O365.
OutlookPrivacyPlugin is BETA 49.

Please let me know if you need any more details.

Thanks,

**Comment by greg-mitchellsxm** [comment]
having the same issue  outlook 2013 32bit

**Comment by Meddington** [comment]
Please attach %AppData%/OutlookPrivacyPlugin/log.txt

**Comment by Chewie9999** [comment]
Meddington - I have attached the entire log to issue #110, which will include this error too.
Thanks!

**Comment by Meddington** [comment]
Added a possible fix in BETA 52

**Comment by Meddington** [comment]
duplicate of #34.  Closing as Such
