### ISSUE TITLE
Office 2013 "Configuration system failed to initialize"

### ISSUE THREAD

**Issue by DiskorD42** [dejavusecurity/OutlookPrivacyPlugin#112]
Hey there
This Plugin used to work nicely, now i always get this Error Message when i start outlook.
When i go to the Add-Ins tab in outlook, verify, decrypt and settings are greyed out, the only thing working is the about button.

I'm using windows 8.1 and Office 2013

Cheers

**Comment by BerndDA** [comment]
had the same issue.
navigate to %appdata%\outlokprivacyplugin
there is a file called log.txt
in the exception there is another config file mentioned. deleted this one and restarted outlook.
hope this helps.
bernd

**Comment by DiskorD42** [comment]
This worked like a charm, thanks a lot!

**Comment by Meddington** [comment]
added to wiki
