### ISSUE TITLE
Support French in localization file

### ISSUE THREAD

**Issue by Lastjp** [dejavusecurity/OutlookPrivacyPlugin#114]
Hello,

It'd be great to have french support as well. 
I'll add the resx file to support them.

Is that ok for you?

**Comment by Meddington** [comment]
Yes this is fine.  Please fork the repository and submit a pull request with your changes.

**Comment by Lastjp** [comment]
Hello Meddington,

I submitted again the https://github.com/Lastjp/OutlookPrivacyPlugin/commit/451878b0a0d0519ed8177cc316390b8df917b862

This is fixing some square characters for french accent. For some reason, the charset did not work well.
Could you take it for your next release.

Based on the latest code that you commited, you did good job:

![capture](https://cloud.githubusercontent.com/assets/15650229/11616284/817da25e-9c77-11e5-9455-65fe06d7c10b.PNG)
