### ISSUE TITLE
Key capabilities detection has issues 

### ISSUE THREAD

**Issue by Lastjp** [dejavusecurity/OutlookPrivacyPlugin#115]
Between release V50 and release V51, I detected a regression with Outlook 2010 and Windows 7.
 I cannot send PGP mail to some of my contact wheras they are correctly listed when I do pgp --list-keys. They disappeared in release V51. 

If I revert to V50, the contact name appears again.

I do not know how many contact name disappeared

**Comment by Meddington** [comment]
That's very strange. There shouldn't be any changes to that portion of the code.

**Comment by Lastjp** [comment]
Hello Meddington,

I'm also reproducing the issue with the release v1 BETA-56.
As soon as I'm reverting v50, it's OK.
What I can see is that the list displayed with all my PGP contacts is not complete.

Is there a way for me to provide you some useful logs to understand the reason?

**Comment by Lastjp** [comment]
I think the issue should come with this new function: GetPublicKeyRing.
For some reason, I should have someone in my contact pgp causing the function to return wrongly. Do you see a way to move formward with my issue?

**Comment by Meddington** [comment]
If you could send me your keyring I can take alook.  meddington at gmail dot com.

**Comment by Lastjp** [comment]
I had few minutes to investigate a bit the issue. I think I understood the main issue. I have some key that do not have flags... I do not know why....

There is already a code to protect this kind of issue but it's not active. I was able to restore the default behaviour by changing a little bit the function IsEncryptionKey by replacing the return false by a continue.
Could you check and review. You plugin is really awesome.
		public bool IsEncryptionKey(PgpPublicKey key)
		{
			// First check key use flags
			foreach (PgpSignature sig in key.GetSignatures())
			{
				var hashedSubPackets = sig.GetHashedSubPackets();
				if (hashedSubPackets == null)
					continue;

				var keyFlags = hashedSubPackets.GetKeyFlags();

				if ((keyFlags & KeyFlags.EncryptComms) > 0)
					return true;

				if ((keyFlags & KeyFlags.EncryptStorage) > 0)
					return true;

				continue;
			}

			// NOTE: Some keys do not have flags set. Instead use
			//       the alg type. But only those specific to encryption.

			if (IsEncryptionAlg(key))
				return true;

			return false;
		}

**Comment by Lastjp** [comment]
Hello,

Hello Meddington,

When I use PGP tool to view properties, I can see the following:

pub  1024D/XXXXX créé : 2001-09-03  expire : jamais      utilisation : SCA
                     confiance : inconnu       validité : inconnu
sub  2048g/XXXXX  créé : 2001-09-03  expire : jamais      utilisation : E

So the keyFlag is correctly filled in the key. I do not have time yet to go deeper to understand why we did not find the keyflags in the plugin. 
Do you have specific trace I can add to investigate?

**Comment by Lastjp** [comment]
I continue investigated the issue, and I confirm that key flag is equals to 0.
I also updated to the latest 1.8.0 BouncyCastle OpenPGP released few days ago.

But the issue does not seem to be here. I used pgpdump to get all details from this specific key, and I confirm that even with this tool, there is no Key Flag set.

I'll suggest an other patch to workaround.

**Comment by Meddington** [comment]
I've committed a patch to the Is*Key functions that may help.  Give it a shot and let me know how it goes.

**Comment by Lastjp** [comment]
Thanks. This is working fine.

Good job.
