### ISSUE TITLE
Error, unable to locate decryption key

### ISSUE THREAD

**Issue by richinek** [dejavusecurity/OutlookPrivacyPlugin#119]
Hello Michael,

I installed Gpg4win 2.2.6 and your Outlook privacy plugin Beta 55. Generated keypairs and tried the Outlook plugin. I created a new email message, encrypted it and sent to my email address. I checked the decryption functionality on the same computer and it was working ok - message has been decrypted. After that I have installed Gpg4win 2.2.6 and Outlook privacy plugin Beta 55 on another computer, imported my public certificate and opened the encrypted message. During the opening an error message appeared - "Error, unable to locate decryption key.". I tried to find solution via Google, but were not successful. Can you give me some advise what's wrong? Not sure, how to pair the Outlook privacy plugin together with Gpg4win/Kleopatra.

Thanks,
Richard

**Comment by Meddington** [comment]
Encryption uses your public key, decryption uses your secret key. If you only imported your public key you will not be able to decrypt messages.  There are many online resources for getting started with GPG/PGP.

**Comment by richinek** [comment]
Thank you very much!
