### ISSUE TITLE
Encrypt broken in Beta36: Error, unable to find recipient key

### ISSUE THREAD

**Issue by sammyxx** [dejavusecurity/OutlookPrivacyPlugin#12]
on Windows 8.1 Update1 x64 with Outlook 2013 x86 and OutlookPrivacyPlugin Beta36 I get the error: "Error, unable to find recipient key <e-mail address from sender>" when sending an encrypted (not signed) mail. It seems the plugin selects the wrong public key for encryption, because the public key from my sender e-mail (referred to the error message) shouldn't be needed at all.

When I add a new key pair to Kleopatra for my sender e-mail, I can send encrypted messages to the previously mentioned recipient (my second e-mail account for testing purposes). However I'm not able to decrypt the message. I get the error that I entered the wrong password, although I'm copying the password from Keepass and Signing works very well with the same certificate and password.
However I'm able to decrypt the message manually via command-line (with the same password) and I get this output:

C:\temp>gpg --decrypt encrypted.txt.pgp

You need a passphrase to unlock the secret key. 
User: "User <recipient e-mail>"
2048-Bit RSA key, ID F691A889, generated 2014-05-08

gpg: encrypted with 2048-Bit RSA key, ID 8644B409, generated 2014-05-08
      "User <sender e-mail>"
gpg: encrypted with 2048-Bit RSA key, ID F691A889, generated 2014-05-08
      "User <recipient e-mail>"
 Valid decrypted message
C:\temp>

This confirms my theory that the plugin selects the wrong key at first, but then uses the correct key for the second attempt. However decryption is only possible over the command-line.

Hope this helps!
Regards,
Sammy

**Comment by Meddington** [comment]
This may be related to how we cached passwords for keys.  I've switched to a callback system that allows different passwords for different keys to be used.

Please check and see if the issue is resolved in latest build.

**Comment by danste** [comment]
Hello,

I'm having the same issue on Windows 10 x64 with Outlook 2016 and beta56 of the privacy plugin.
I'm having a 1024 Bit RSA key...
