### ISSUE TITLE
decryption in Outlook 2016 works but encryption does not

### ISSUE THREAD

**Issue by Buerzli** [dejavusecurity/OutlookPrivacyPlugin#120]
I have installed the OutlookPrivacyPlugin on Outlook2016 and the decryption works fine. Encryption creates the following error:

![outlook_privacy_plugin_error_1](https://cloud.githubusercontent.com/assets/15905576/11237964/02d58e00-8de3-11e5-8a97-ca9cbfdd3a4f.jpg)

**Comment by Meddington** [comment]
Search the closed issues for "resources".
