### ISSUE TITLE
Some french translation had square: Iso Encoding issue

### ISSUE THREAD

**Issue by Lastjp** [dejavusecurity/OutlookPrivacyPlugin#125]
Hello Meddington,

I submitted again the Lastjp@451878b

This is fixing some square characters for french accent. For some reason, the charset did not work well.
Could you take it for your next release.

Based on the latest code that you commited, you did good job:

capture
![capture](https://cloud.githubusercontent.com/assets/15650229/11616309/c8cdb75c-9c77-11e5-9138-2a29e9edf0f5.PNG)

**Comment by Lastjp** [comment]
I'm quite new with GIT, and the pull request should not have all these files.
The two delvieries that should be taken are the two:
@Lastjp	Fix square in French Translation	451878b
 @Lastjp	Fix Traduction Française	b23aeb2

Is it ok for you to take only these or do you need me to do something specific for you to merge?

**Comment by Meddington** [comment]
Please correct the pull request. Google is your friend :)
