### ISSUE TITLE
Sending email throws error

### ISSUE THREAD

**Issue by rmarsollier** [dejavusecurity/OutlookPrivacyPlugin#130]
Hello,
Sending email (s/mime) from sender to receiver throws error:
Error, unable to find recipient key "**sender** adress"

Option "Encrypt mail to Self" is disabled.

For information, the error threw is with the address in uppercase whereas in the certificate I use, this very adress is lowercase.

Versions:
Outlook : Pro + 2010 (14.0.7163.5000)
OPP : BETA56
GnuPG4Win : 2.3.0

Here is the log collected in %AppData%
-------- 12/16/2015 3:41:24 PM --------
EncryptEmail

Deja.Crypto.BcPgp.PublicKeyNotFoundException: Error, unable to find recipient key "sender adress".
   at Deja.Crypto.BcPgp.PgpCrypto.Encrypt(Byte[] data, IList`1 recipients, Dictionary`2 headers)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.EncryptEmail(Byte[] data, IList`1 recipients)

**Comment by Meddington** [comment]
Are you actually using S/MIME or are you using OPP to encrypt the outbound email?  OPP doesn't perform S/MIME which is a different encryption method from PGP/GPG.

**Comment by rmarsollier** [comment]
Oh, mybad, i misread the description, so OPP is not what i am looking for? It's not going to answer my need? If so, close this ticket, sorry for the inconvenience.

**Comment by Meddington** [comment]
What's your need?

Cheers,
Mike

**Comment by rmarsollier** [comment]
Well, I talked to my managers, and we will use plain PGP/mime instead of S/MIME with certs of our CA, so I simplified the problem :)

BTW : in the main description : "Decrypting in preview pain" should be "Decrypting in preview *pane*".

**Comment by Meddington** [comment]
Closing as duplicate of #123
