### ISSUE TITLE
Installer Zip File Hash?

### ISSUE THREAD

**Issue by cyberis** [dejavusecurity/OutlookPrivacyPlugin#131]
I'm a little surprised that you do not publish a hash of the installer zip file. I'm sure the installer is signed but how do I know the zip file wasn't corrupted during download without a hash of it. Seems like that would be a good idea. I didn't see this issue addressed before. Did I miss that?

**Comment by Meddington** [comment]
The code itself is signed and will not not run if corrupted.  Shouldn't be any need to post hashes.  Zip also has a CRC included in it to identify corruption.

I would recommend using https to download :)
