### ISSUE TITLE
Outlook constantly asks to save changes when closing viewer window

### ISSUE THREAD

**Issue by andrewgdotcom** [dejavusecurity/OutlookPrivacyPlugin#133]
When I try to close the viewer window of a signed, verified message, outlook always asks me this:

"The properties of the message "......" have been changed. Want to save your changes to this message?"

The message has not been changed (by me, anyway).

**Comment by Meddington** [comment]
This is occurring because we insert text into the message window with details about the signature verification. As long as we are modifying the message text to provide this information there doesn't seem to be away to prevent the dialog from popping.
