### ISSUE TITLE
Cryptix OpenPGP incompatability

### ISSUE THREAD

**Issue by DrFrankBV** [dejavusecurity/OutlookPrivacyPlugin#14]
Outlook2013:
The switch settings are now stored in this version and the switch successfully suppresses the error message that was there before, but the mail is not decrypted.

Is it possible only the error is suppressed, but the plug-in still does not attempt with the decryption of the mail?

**Comment by Meddington** [comment]
Should be fixed in BETA 53. Finally found a reproduction case. Issue was related to the 10 year old Cryptix pgp library for java.

**Comment by Meddington** [comment]
Please re-open if bug is not fixed.
