### ISSUE TITLE
show decrypted message in preview

### ISSUE THREAD

**Issue by LinuxKernel1** [dejavusecurity/OutlookPrivacyPlugin#143]
Office: Professional Plus 2013/64bit
Plugin: v1 BETA-56
OS: Windows 10 Pro/64bit

After entering the passphrase emails are only decrypted when you open them in a new/seperate window. Cooler would be if the messages gets also decrypted and shown in the preview when you just select them in the list.

**Comment by Meddington** [comment]
duplicate
