### ISSUE TITLE
Use secure SHA-512 and AES-256 by default

### ISSUE THREAD

**Issue by seanthegeek** [dejavusecurity/OutlookPrivacyPlugin#148]
SHA-1 is [insecure and deprecated](https://en.wikipedia.org/wiki/SHA-1#The_SHAppening) Using AES-256 reportedly improves resistance to certain quantum attacks.

**Comment by muibusan** [comment]
+1

**Comment by Meddington** [comment]
You can change the hash and encryption method.  However, the default settings allow for reasonable backwards compatibility which is needed by most users.
