### ISSUE TITLE
Outlook considers plugin slow to start

### ISSUE THREAD

**Issue by dmjones500** [dejavusecurity/OutlookPrivacyPlugin#15]
Outlook has identified this plugin as being slow to start, complaining at a 2.230 second start time.

To be honest, I think that's perfectly fast enough. But I had to tell Outlook to always enable the plugin, otherwise it chose to disable it by default.

More of an FYI than a bug, but worth bearing in mind in case you do ever more computationally expensive things at plugin start-up.

**Comment by mschnecke** [comment]
maybe ngen?

**Comment by Meddington** [comment]
Closing due to lack of reproduction or additional information.
