### ISSUE TITLE
Plugin does nothing

### ISSUE THREAD

**Issue by sirber** [dejavusecurity/OutlookPrivacyPlugin#151]
On WIndows 10 x64, Office 2016 x64, when I press sign it does nothing. GPG4Win is installed, my key is loaded inside kleopatra.

**Comment by Meddington** [comment]
Are you editing from the preview screen or in a new window?  OPP doesn't work in the preview view.

**Comment by sirber** [comment]
In a new message, in a popup. WHen I press sign, the message is changed from html to plain, the content blinks, then nothing. No popup for keypass, nothing. Nothing in the logs also.

**Comment by Meddington** [comment]
And I'm assuming it was received w/o signature?

**Comment by Meddington** [comment]
Oh, FYI, the signing occurs on send.  If you haven't clicked the Send button then nothing is supposed to happen yet (aside from changing the formatting style).

**Comment by sirber** [comment]
Oh? I'll retry then :) I thought it would change my text.

--
Stéphane Bérubé


Date: Fri, 1 Apr 2016 13:24:51 -0700

**Comment by sirber** [comment]
I did a test, and it worked. When I press Send, I get the popup to enter my keypass then the sent email is signed. Thank you!
