### ISSUE TITLE
wrong key attached

### ISSUE THREAD

**Issue by Dandyx** [dejavusecurity/OutlookPrivacyPlugin#152]
Hi there,

OPP still attaches the wronk key. 
Installation guide says:
"=== 4. Setting custom keyring location (OPTIONAL)
Outlook Privacy Plugin should automatically find your keyrings. However, if they are located in a non-standard location or gpg4win is not being used, a custom location for keyrings can be set via the +GNUPGHOME+ environmental variable. After setting the environmental variable, Outlook must be restarted."

What is the  >>> +GNUPGHOME+ environmental variable <<< and where do I set it?

Thanks,
Felix
------
Win7
64bit
Outlook 2013 - 64bit

**Comment by Lastjp** [comment]
Google is always your friend.

https://wiki.archlinux.org/index.php/GnuPG
https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration-Options.html

**Comment by Dandyx** [comment]
Sorry, too compliacated. Just want my encryption to work without programming course. Using differernt tool now. Bye bye
