### ISSUE TITLE
Sign in anything but SHA1

### ISSUE THREAD

**Issue by Hellman109** [dejavusecurity/OutlookPrivacyPlugin#16]
Hi,

It appears that even if you change your crypto settings in gpg4win your plugin will always sign emails in SHA1.  Is it possible to change this at all? as I could not find a way.

I set my gpg.conf file to have:
personal-cipher-preferences AES256 AES192 AES CAST5 3DES
personal-digest-preferences SHA512
cert-digest-algo SHA512
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 BZIP2 ZLIB ZIP Uncompressed

Yet it still signs emails as SHA1

**Comment by sanddweller** [comment]
Hi,
also need option to set desired cipher. OPP appears to default to CAST5 for me. Need AES256. Changed gpg.conf settings without effect. :( Later found this post.

**Comment by Meddington** [comment]
Added this as an option in BETA 42.
