### ISSUE TITLE
OutlookPrivacyPlugin-BETA-56-Setup - plugin not showing - resources not installed

### ISSUE THREAD

**Issue by stratfordmanagement** [dejavusecurity/OutlookPrivacyPlugin#166]
I was using OutlookPrivacyPlugin-BETA-56 for a while, but I believe an update of Outlook broke it.
OutlookPrivacyPlugin-BETA-56 is installed as shown in "Programs and features", but not showing in new mail dialogues.

*I tried reinstalling it several times as user and as administrator, rebooting every step of the way.
*I tried running OutlookPrivacyPlugin.vsto but get the same errors as issue #106, I then added the regkeys to said places, again rebooting and this tried as normal user and administrator. 
*tried adding the missing files OutlookPrivacyPlugin.vsto from the repository but got stuck on on /de/OutlookPrivacyPlugin.resources.dll as I couldn't find this on your site.
*I tried clean install, cleaning all regkeys and cleaning up with an uninstaller.

To no avail...

**Comment by Meddington** [comment]
What's your os and office version?  I'm in win10 office 2016.

**Comment by stratfordmanagement** [comment]
Hi,

I'm on win10 x64 and office 2013, I do have the option to upgrade to office 2016

**Comment by Meddington** [comment]
I haven't used 2013 on Windows 10 myself, but I was using it on win 8.1 up
to about 1 month ago without any problems.  Is the plugin showing in your
add-ins list (File -> Manage Add-ins)?

Cheers,
Mike

**Comment by stratfordmanagement** [comment]
Oh my god...
Since I have Office 365, I was directed to the on-line management page while clicking to add-ins, and nothing was shown. However I also have the button Com- add-ins where I can find the slow and disabled add-ins. Outlook was kind enough to disable the add-in. I enabled it and voila.

Shamefully thanking you!
