### ISSUE TITLE
Decrypt and verify buttons unavailable (BETA-37)

### ISSUE THREAD

**Issue by dmjones500** [dejavusecurity/OutlookPrivacyPlugin#17]
When I open encrypted email I find the Verify and Decrypt buttons are greyed-out/unavailable. If I copy/paste the email contents to a file, I can successfully decrypt the message using gpg on the command line.

This problem doesn't exist in BETA-35 or BETA-36.

**Comment by Meddington** [comment]
Thanks for the code, super helpful!

**Comment by Meddington** [comment]
This will be in release 41.
