### ISSUE TITLE
"Attempted to read past the end of the stream" when reading public key ring

### ISSUE THREAD

**Issue by andrewgdotcom** [dejavusecurity/OutlookPrivacyPlugin#2]
The following message gave me an error when trying to verify. (beta 35)

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

foo

-----BEGIN PGP SIGNATURE-----
Version: Outlook Privacy Plugin

iQFJBAEBAgAzBQJTSAFvLBxBbmRyZXcgR2FsbGFnaGVyIDxhbmRyZXcuZ2FsbGFn
aGVyQHdhcmQuaWU+AAoJENW/k7AUpJcAqZYIAJB/rerwmhRskVH/URq0o6rz5/kn
Fc02H4c8bZjeVcxt7Iz77WbybpooYc0wAnpWj2/jY8gkO6W3wr8hCMj8pfdW7OMr
5qh1pmWxcdGmiwQRB8IZvzalihmavENezH8B5GsewtjGq/g99h0Kdlf2jcrcZ/h9
Qc2c2yAyOFvHCVhznNZj5V0EvQ0JJQw46W+wPnGtve6ELXJLBfXUpvd1gNRKoCzX
3TGYi+msnlKjFoM3pPxXfurlbP9KE53cgxik8nxhsh3fCouHivrTxqo1y3Vq3j9V
koXd0CPraWMcp2s1mcLxqoUA1XEaXWbuC9nk6KuDJMicNU+0n7afqakS0og=
=tIu9
-----END PGP SIGNATURE-----

**Comment by Meddington** [comment]
Please re-open if this is still an issue. I haven't been able to cause a reproduction.

**Comment by andrewgdotcom** [comment]
Michael,

Sorry to say that yes it is. I'm getting this every time I try to open a
signed message. I'm using beta 46.

**Comment by andrewgdotcom** [comment]
I'm not sure if this is the same issue or a different one, but I'm also
getting "Object reference not set to an instance of an object" if the
message I'm verifying has a PGP block that has been > quoted.

Andrew.

**Comment by andrewgdotcom** [comment]
Sorry, one more thing. :-) I'm actually testing this on outlook 2010 at
the moment, not 2013 as the bug title says. (I may have been using 2013
on another machine at the time I opened the ticket).

**Comment by Meddington** [comment]
Thanks for the update. I'm going to open a new issue for the quoted issue.

**Comment by andrewgdotcom** [comment]
On 24/05/15 06:33, Michael Eddington wrote:
> Please re-open if this is still an issue. I haven't been able to cause a
> reproduction.

I'm using the latest beta-49 and this is still here. Similar behaviour
to #4, although I don't get a stack trace in this instance.

Andrew.

**Comment by andrewgdotcom** [comment]
I upgraded from 2010 32-bit to 2013 64-bit and the error is still here.

**Comment by Meddington** [comment]
@andrewgdotcom - The latest 55 build has an "Enable debug tracing" option in settings.  Could you enable that and then email or post up your %appdata%\outlookprivacyplugin\*.txt files (email is meddington at gmail dot com).

**Comment by andrewgdotcom** [comment]
Michael,

I think this issue can be closed. I have since rebuilt my public key ring from backups (a few times!) and the issue has not recurred. I suspect it may have been a keyring corruption issue.

Sorry for the noise.
