### ISSUE TITLE
replies to encrypted emails should encrypt as default

### ISSUE THREAD

**Issue by BuildTheRobots** [dejavusecurity/OutlookPrivacyPlugin#20]
At the moment it's extremely easy to decrypt an email, reply to it and completely forget to encrypt your reply.

This tends to have the downside of exposing the entirety of the encrypted conversation (due to quoted replies at the bottom), so it's somewhat worse than if you'd just sent a single email unencrypted.

An option to automatically encrypt replies to encrypted emails would make it harder for me to be an idiot. -with thanks.

**Comment by Meddington** [comment]
Should be resolved in next release
