### ISSUE TITLE
How to reinstall OutlookPrivacyPlugin?

### ISSUE THREAD

**Issue by tomtel** [dejavusecurity/OutlookPrivacyPlugin#22]
Hi,

I'm using BETA-37 with Outlook 2010 on Windows 7 Prof.

I tried to reinstall the OutlookPrivacyPlugin after deleting the Plugin within the Outlook --> Add-Ins-Window --> COM-Add-Ins-Window. 

After the reinstall with user or administar rights I've got the message "The plugin is already installed" but the plugin is not shown within the Add-Ins-View and there are no plugin-buttons shown in the email window.

What goes wrong?

Bye

tomtel

**Comment by Meddington** [comment]
I can't reproduce this behavior. The plugin is using a generated installer from visual studio and seems to work on every machine I've looked at.

**Comment by mpetr** [comment]
Have the same problem with all our computers. **Finally found the solution.**
The **installer have to be started from within the user's context**. It will prompt for admin rights later, eventually. Or if the user have the administrative rights for computer, it will go through even without additional prompt.
But if you start the installer like "run as administrator" or in the context of different user, the plugin will show up in programs but will not load in targeted user's Outlook
