### ISSUE TITLE
BETA38 Installation fails

### ISSUE THREAD

**Issue by aestheticus** [dejavusecurity/OutlookPrivacyPlugin#23]
The installation fails right at the beginning with "The following Microsoft Office solution cannot be loaded because a compatible version of the .NET Framework is not installed."

Although .NET 4.5 (4.5.50709) Full certainly is installed. In the Manifest files it requires 4.5 (4.0.30319), which makes no sense in my view. Changing the Manifest to the proper version breaks its signature.

**Comment by Meddington** [comment]
New installer, lowered .net requirement to 4.0
