### ISSUE TITLE
Mails are saved in inbox unencrypted

### ISSUE THREAD

**Issue by SystemCheater** [dejavusecurity/OutlookPrivacyPlugin#25]
Hi folks!

The problem:
Once an email was decrypted the message is saved in the inbox. In my case I'm using IMAP which synchronizes the inbox with the mail server. Thus the mail server has now my unencrypted message. (And that's what I want to avoid.) Would be great to have a setting "do not save to inbox" or similar.

Thank you for your effort to create finally a usable and free encryption plugin for outlook. I'm currently playing around with OPP to give it to friends as recommendation for email encryption.

Have a nice day,
SystemCheater

**Comment by Meddington** [comment]
fixed in v40 to be posted shortly.

**Comment by tx3eh8IUD1** [comment]
Oh no. Why can't I opt to have it permanently decrypted? Outlook search and a host of other functions does not function properly when the decryption cannot be safed. That was actually a very useful feature. Now I have to go back to v.38 - could you please make the "don't decrypt permanently" feature optional?!
