### ISSUE TITLE
Installation process as one executable

### ISSUE THREAD

**Issue by SystemCheater** [dejavusecurity/OutlookPrivacyPlugin#26]
Hi privacy fans!

Still playing around I noticed that I've still to do execute some more installations:
* GPG4Win Installer
* .NET4.5 Framework
* Unlock OPP
* OPP Installer
Couldn't we put it in one installer?

Btw what is the presinstallation of .NET4.5 for? I saw it's already in the prerequesites of the OPP and installs well without preinstalled .NET4.5 on a fresh Windows7Pro x64 with Outlook 2010.

As a side effect it would be possible to hook in a wizard for the intial configuration of gpg so the user can start with sending encrypted emails right after installation.

Greetings,
SystemCheater

**Comment by Meddington** [comment]
Resolving the need for 4.5 and unlocking OPP. However we will not include GPG4Win in our installer.
