### ISSUE TITLE
Localization of the UI (esp. German)

### ISSUE THREAD

**Issue by SystemCheater** [dejavusecurity/OutlookPrivacyPlugin#27]
Hi guys,

another thing:
It would be great to have localization, in my case German. 

This makes the feeling of the plugin much better for non IT-guys like girl-friend, sister or football-friends... and leads to more people using the plugin (and writing me encrypted mails).

(I could do the German part :-) .)

Have a nice weekend,
SystemCheater

**Comment by Meddington** [comment]
If someone can provide a translation of messages used by OPP then I will look into how to support multiple languages. I imagine this would be better than using google translate :)

**Comment by Baebeca** [comment]
Where can I find the .pot file?
Then i will create native translations

**Comment by Meddington** [comment]
C# doesn't make use of pot files. Resources are kept in resx files. There is a core resx in the OutlookPrivacyPlugin/Languages folder (just added) and each Form has it's own resx file. There are a couple strings I wasn't able to localize yet such as the ribbon labels.

To localize a new file with the extension .de.resx is added for each resource file containing the translated strings.

So for example:

  Localized.de.resx
  FormSettings.de.resx

etc.

**Comment by Baebeca** [comment]
Ok Thanks - i will create The german translations

**Comment by Baebeca** [comment]
@Meddington 
We need to duplicate the whole file? or only the data attributs?
Please check the new file in the language folder - if it is correct and you setup a translation file for the other forms, i will translate These Files soon.
you find tue new file in my pull request #79

**Comment by Meddington** [comment]
The entire file is duplicated and named with the locale.  I have merged your pull request and updated the project file to include the Localized.de.resx. I think it should automatically get used now if the language is German.

**Comment by Baebeca** [comment]
@Meddington 
It works very fine! - I've attach a Screen
Please let me know if you are able to create Language Files for the rest.

Thanks so far - G00d J0B!

**Comment by Meddington** [comment]
Nice!

There are also the resx files for each of the forms. Form*.resx.  These contain strings used in the dialog boxes such as settings and key selection. The same method can be used, create new file with ".de.resx" extension.

**Comment by Baebeca** [comment]
i cant find new .resx files in the translation dir in your current commit?

**Comment by Meddington** [comment]
Sorry I should have been more clear as to the location.  They are in the OutlookPrivacyPlugin folder (https://github.com/dejavusecurity/OutlookPrivacyPlugin/tree/master/OutlookPrivacyPlugin). 

https://github.com/dejavusecurity/OutlookPrivacyPlugin/blob/master/OutlookPrivacyPlugin/FormKeySelection.resx
https://github.com/dejavusecurity/OutlookPrivacyPlugin/blob/master/OutlookPrivacyPlugin/FormPassphrase.resx
https://github.com/dejavusecurity/OutlookPrivacyPlugin/blob/master/OutlookPrivacyPlugin/FormSelectLineWrap.resx
https://github.com/dejavusecurity/OutlookPrivacyPlugin/blob/master/OutlookPrivacyPlugin/FormSettings.resx

**Comment by vollme-s** [comment]
translated some stuff
for my german colleagues: please Review my stuff

**Comment by Baebeca** [comment]
@vollme-s thanks! i will Review your translations

**Comment by Baebeca** [comment]
@vollme-s @Meddington 

File: OutlookPrivacyPlugin/FormKeySelection.de.resx
Line: 341

```xml
<data name="buttonSend.Text" xml:space="preserve">
    <value>Senden</value>
</data>
<data name="&gt;&gt;buttonSend.Name" xml:space="preserve">
    <value>buttonSend</value>
</data>
```

is the attribute name correct? (name="&gt;&gt;buttonSend.Name")

**Comment by Meddington** [comment]
I assume so, they are auto generated by visual studio.

**Comment by Baebeca** [comment]
can we remove these chars?
German translation doesnt work in the current build

**Comment by nottheend** [comment]
I think localization is a great thing.

Until today the names of the items used in Outlook 2016 are still in english, although I am using a german version.

@Meddington or @Elompenta 
Is there a possibility to continue translation?

**Comment by Elompenta** [comment]
@nottheend 
I love this project and will support all the time!
At the moment i have a big timing problem to spend my work to this Project :(

I hope i'm back in the next months to work on this issue.

Greetz and all the best
