### ISSUE TITLE
Attaching private key

### ISSUE THREAD

**Issue by Genis-Sage** [dejavusecurity/OutlookPrivacyPlugin#29]
I testes PGP with a friend.
He is running Thunderbird with Enigmail under Linux (I think Ubuntu, but not sure).

With the key which is attached by the button "attach key", he had some problems,
so he could not verify my signed messages.

Then I directly exported my private key from Kleopatra,
and sent him that one, and now it works fine.

**Comment by Reddi82** [comment]
I'm doesn' checked the key, but I think I have the same problem. If I compare my exported public key from kleopatra with the automaticly public key at the attachement, It seems the same key on first view. But only the last 4-10 characters are different...

**Comment by Meddington** [comment]
You would never want to attach the private key, only the public.  By default this is what Kleopatra is likely doing.

I've improved the attach key function and tested with enigmail and Kleopatra. Seems to be working OK.

Included in next release.
