### ISSUE TITLE
Incorrectly using master key instead of sub-key for encryption

### ISSUE THREAD

**Issue by txr13** [dejavusecurity/OutlookPrivacyPlugin#30]
Windows 7 Ultimate x64 SP1
Office 2010 Professional Plus
GPG4Win 2.2.1
.NET Framework 4.5.1

I'm attempting to sign an email to send outbound. I am correctly prompted for my passphrase, but after entering it, I get this error message. The email is neither signed nor sent.

The master key for my keypair is not present on this machine; it is kept offline for security. I have two subkeys present on this machine--one for encryption, and one for signing. This works correctly when invoked by Enigmail (via Thunderbird) or by command-line gpg.

**Comment by Meddington** [comment]
Should be fixed in BETA 44. Updated code to use sub-key over master when present.

**Comment by txr13** [comment]
Confirmed fixed in BETA 44.

Note I still can't encrypt outgoing mail due to issue #31. I also cannot decrypt or verify inbound signed or signed/encrypted email. I can successfully decrypt inbound encrypted/unsigned email.
