### ISSUE TITLE
BETA v38 cannot be installed with .Net 4.5.2

### ISSUE THREAD

**Issue by HorstSchnetzler** [dejavusecurity/OutlookPrivacyPlugin#32]
I've installed the .net Framework current version 4.5.2 on a windows7-Enterprise x64 - system before installing the BETA v38.

Trying to install the beta using the setup.exe leads to the following error-message:
![screenshot 007](https://cloud.githubusercontent.com/assets/1880093/3977441/d9c3e6da-2838-11e4-9529-3e482a1ddbcf.png)

Do I have to deinstall v4.5.2 and reinstall the older version 4.5 of .Net to let magic happen?

**Comment by Meddington** [comment]
I removed the .net version requirement. Please try the latest installer.
