### ISSUE TITLE
the value of the type property can not be parsed, the error is: Assembly microsoft.business.aplications.fba, version = 14.0.0.0 Culture = neutral PublicKeyToken = 71e9bce111e9429c or one of its dependencies not load them. The system can not find the file specified.

### ISSUE THREAD

**Issue by basd82** [dejavusecurity/OutlookPrivacyPlugin#33]
When i try to install the plugin on win 8.1 with office 2013

The error messages is in dutch sorry : 
see this image

![schermafdruk 2014-08-20 12 19 15](https://cloud.githubusercontent.com/assets/1219705/3979371/8c7cd858-2853-11e4-9c25-340adec89d53.png)

with some help of google translate it becomes this:

the value of the type property can not be parsed, the error is: Assembly microsoft.business.aplications.fba, version = 14.0.0.0 Culture = neutral PublicKeyToken = 71e9bce111e9429c or one of its dependencies not load them. The system can not find the file specified (C:\Program Files\Common Files\microsoft shared\VSTO\10.0\VSTOInstaller.exe.config)

I checked but the file is there

**Comment by Meddington** [comment]
Thanks for the info.
