### ISSUE TITLE
Accessing MIME message body throws error

### ISSUE THREAD

**Issue by basd82** [dejavusecurity/OutlookPrivacyPlugin#34]
Does de privacy plug reconice detached signitures.

If so why can 't verify them ?

**Comment by Meddington** [comment]
PGP/Mime signatures are supported for verification. I've tested with Apple Mail w/GPGMail and Thunderbird w/Enigmail.

Could you expand on what your seeing?

**Comment by Meddington** [comment]
I've recently improved some of the key methods, perhaps it will work now. Otherwise please expand on the issue you are seeing.  Do you get a message "** Invalid signature" ?

**Comment by mygithuber** [comment]
Beta-46: Only signing with PGP/Mime is giving "** Invalid signature from "" with KeyId " at recipient's Outlook with OPP-b46.
NOT working, if sender is using PGP/Mime, with or without German Umlaute üöäß in message body. Recipient's Outlook shows message body with separate attachment.sig file.
Regards!

**Comment by Meddington** [comment]
For the original issue regarding the crash/exception that occurs, beta 52 has a possible fix for this issue.  This does not address invalid signatures occurring which is a separate issue.

**Comment by Meddington** [comment]
Please re-open if issue persists

**Comment by jafse** [comment]
Hello, same problem as Outlook 2016 with BETA-56. Mails with a signature by third one or by myself are always marked as "invalid signature". Encrypted mails by the same senders are marked as "valid signature". The signature and encrypting are done with your plugin.
