### ISSUE TITLE
Can't install, got error in install [BUG?]

### ISSUE THREAD

**Issue by NikoIronLions** [dejavusecurity/OutlookPrivacyPlugin#35]
Error information:

__Orginal version__[fi_FI]

Nimi: 
Lähde: file:///C:/Users/Niko/Desktop/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin.vsto

************** Poikkeuksen teksti **************
System.Deployment.Application.InvalidDeploymentException: Käyttöönotolla ja sovelluksella ei ole samat suojausvyöhykkeet.
   kohteessa Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   kohteessa Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

__TRANSLATED VERSION__ [en_US]

Name: 
Source: file:///C:/Users/Niko/Desktop/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin.vsto

************** exceptional text **************
System.Deployment.Application.InvalidDeploymentException: The adoption and the application does not have the same security zones.
   object Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   kohteessa Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

__

I hope we can solve this problem.

Regards,
Niko

**Comment by Meddington** [comment]
Please read the install instructions, especially about unblocking the zip. Also make sure your not installing from a network/usb drive.
