### ISSUE TITLE
"Attach key" - OPP seems to encrypt the public key

### ISSUE THREAD

**Issue by patschi** [dejavusecurity/OutlookPrivacyPlugin#36]
When writing an email I enabled the options to sign, encrypt and attach the key to the mail. After I sent the key, the recipient got the mail, but the attached "public_key.gpg" was also encrypted, which does not make really that much sense in my optinion...

![2014-10-05_201352-busqt](https://cloud.githubusercontent.com/assets/2029878/4519446/661c722c-4cbb-11e4-91a2-78546ecb9d6c.png)

**Comment by Meddington** [comment]
If you encrypt the email it will encrypt the key as well...
