### ISSUE TITLE
Decrypted messages forever

### ISSUE THREAD

**Issue by dsalinasmx** [dejavusecurity/OutlookPrivacyPlugin#37]
each encrypted message (sent or received) ... once decrypted the message firs, is stored decrypted forever. Reviewing the code the function mailItem.Close(Microsoft.Office.Interop.Outlook.OlInspectorClose.olDiscard); is not working apparently by an ambiguity in Close Event.. and the olDiscard applied once decrypted message
Its possile to discard the decryption once read the mail ?

**Comment by tx3eh8IUD1** [comment]
(I just want to add that I use pop and I appreciate the permanent decryption)

**Comment by tx3eh8IUD1** [comment]
This is a duplicate of the issue #25 
(https://github.com/dejavusecurity/OutlookPrivacyPlugin/issues/25)
