### ISSUE TITLE
Decryption key not found, unicode related?

### ISSUE THREAD

**Issue by CaptainCannabis** [dejavusecurity/OutlookPrivacyPlugin#38]
Hi

there seems to be an issue with email contacts containing special chars like " r` " in the first or lastname. I had to get rid off all the saved contacts in outlook belonging to that specific person. After that "kleopatra" found the matching keys and everything worked.

**Comment by Meddington** [comment]
first or last name should not matter, only the internet email address.  Did the email addresses have unicode characters in them?

**Comment by Meddington** [comment]
Closing as non-repro
