### ISSUE TITLE
Select recipients dialog box empty

### ISSUE THREAD

**Issue by andrewgdotcom** [dejavusecurity/OutlookPrivacyPlugin#4]
When I try to send myself an encrypted message, it prompts me to "select recipients" but the list is empty. I have the correct key(s) installed in Kleopatra.

Signing works. I'm using beta 35

**Comment by Meddington** [comment]
Is this still an issue? Are you connected to an exchange server or pop3/imap?

**Comment by mickopp** [comment]
it seems I have a similar problem with latest BETA-44.
I can only select keys from recipients with RSA keys,
Users with DSA/ELG do not show up in the recipient list.

**Comment by Meddington** [comment]
I was able to reproduce the issue using DSA/ELG keys. Fixed in BETA-45.

**Comment by mickopp** [comment]
Hi Meddington,

tried BETA-45 and some more key do show up. But unfortunatly many of my recipient keys do not show up.
All are DSA/ELG. I currenty try to compare and see where is the difference in the keys that show up vs. keys that do not show up.
The only difference I could find so far is: Keys which do not show up have additional key usage "authentication" - but my short tests did not show a difference with newly generated keys (including auth) and DSA/ELG. Only difference I cannot generate "old" keys with 1024bit DSA - only tested with 2048bit DSA - 2048 ELG.

Old keys which do not show up seem to be 1024 bit DSA with additional key usage "authentication"

Any hints how I could debug this issue ?

**Comment by Meddington** [comment]
Could you send me one of the offending keys?  meddington at gmail dot com, or just stick in this issue thread.

**Comment by Meddington** [comment]
Okay this will be fixed in BETA-46. Some keys do not have key usage flags set.

**Comment by mickopp** [comment]
Hi Meddington,
works now for me with BETA-46
many thanks !!!!

**Comment by Meddington** [comment]
@andrewgdotcom - did this solve your issue as well?

**Comment by andrewgdotcom** [comment]
I now get "attempted to read past the end of the stream"...

**Comment by Meddington** [comment]
@andrewgdotcom - When does this error occur? Before the select recipients dialog, after or during?

**Comment by andrewgdotcom** [comment]
On 31/07/15 01:18, Michael Eddington wrote:
> @andrewgdotcom <https://github.com/andrewgdotcom> - When does this error
> occur? Before the select recipients dialog, after or during?

Immediately after I click "send", before any other dialogs. See attached.

Andrew.

**Comment by andrewgdotcom** [comment]
Hm. Attachments by email don't seem to work. Trying the web interface...
![endofstream](https://cloud.githubusercontent.com/assets/617742/9091738/c11f3510-3b99-11e5-96f3-3b15ed05a354.PNG)

**Comment by andrewgdotcom** [comment]
I upgraded from 2010 32-bit to 2013 64-bit and the error is still here.

**Comment by Meddington** [comment]
Closing as this seems to be a duplicate of existing bugs. Origional issue resolves.
