### ISSUE TITLE
OnePassSignature was not found

### ISSUE THREAD

**Issue by github-kevind** [dejavusecurity/OutlookPrivacyPlugin#40]
In Issue 97:	OnePassSignature was not found, you asked for the output of pgp2 with packet descriptions.  This is NOT the simple email that was in issue 97 from the Google Code Project, but I thought it might help.  

Received encrypted message

Hit Decrypt button.  OPP throws a "Error, OnePassSignature was not found!" message.

Output from gpg2.exe --list-packets test.asc

:pubkey enc packet: version 3, algo 16, keyid 1B2C304D34EECB3C
        data: [2048 bits]
        data: [2048 bits]
:pubkey enc packet: version 3, algo 16, keyid C491F04A18F25DCB
        data: [1022 bits]
        data: [1023 bits]

You need a passphrase to unlock the secret key for
user: "XXXXX <xx.xx@xx.com>"
1024-bit ELG key, ID 18F25DCB, created 2009-01-16 (main key ID 42747CA0)

:pubkey enc packet: version 3, algo 1, keyid 81EAED7FBF55B4AA
        data: [2044 bits]
:pubkey enc packet: version 3, algo 1, keyid 46FE376B08B83D45
        data: [1021 bits]
:pubkey enc packet: version 3, algo 1, keyid 71A9136D3B741A02
        data: [2047 bits]
:encrypted data packet:
        length: 2412
gpg: encrypted with RSA key, ID 3B741A02
gpg: encrypted with RSA key, ID 08B83D45
gpg: encrypted with RSA key, ID BF55B4AA
gpg: encrypted with ELG key, ID 34EECB3C
gpg: encrypted with 1024-bit ELG key, ID 18F25DCB, created 2009-01-16
      "XXXXX <xx.xx@xx.com>"
:compressed packet: algo=1
:signature packet: algo 1, keyid 2249A77C44880111
        version 3, created 1414685503, md5len 5, sigclass 0x01
        digest algo 8, begin of digest 89 ec
        data: [2047 bits]
:literal data packet:
        mode t (74), created 0, name="",
        raw data: 5339 bytes
gpg: WARNING: message was not integrity protected

**Comment by Meddington** [comment]
That does help. How did you generate it?  Post PGP 2.6 there should always be a one-pass packet in the message. So far I've been unable to get gnupg to generate one w/o.

**Comment by Meddington** [comment]
Finally got this reproducing and fixed. Had to install MSDOS and PGP 2.6.  Crazy!  You should report to whoever is generating those emails to upgrade.

**Comment by Meddington** [comment]
PS- Will be in BETA 44
