### ISSUE TITLE
Imposible to decryped

### ISSUE THREAD

**Issue by fidel1** [dejavusecurity/OutlookPrivacyPlugin#41]
I use win7 x64, outlook 2013 x64, and your OPP beta 38. Keys are RSA 2048 bit generated by Kleopatra. I sent one encrypted (not signed) email from address 1 to address 2, both installed in outlook. I encryp both addresses (1 and 2). Outlook receives both accounts and therefore in the inbox there are two new messages. It is impossible to decryp the sent message as well as the two received messages. It allways shows the same error: Incorrect passphrase possible entered. Please explain. Thanks.

**Comment by Meddington** [comment]
closing as duplicate of #12.
