### ISSUE TITLE
Can't install in Windows 8

### ISSUE THREAD

**Issue by seifreed** [dejavusecurity/OutlookPrivacyPlugin#44]
I get the next error

Nombre: 
De: file:///C:/Users/Marc Rivero L%F3pez/Downloads/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin.vsto

************** Texto de la excepción **************
System.Deployment.Application.DeploymentDownloadException: No se realizó la descarga de file:///C:/Users/Marc Rivero L%F3pez/Downloads/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin-BETA-38/OutlookPrivacyPlugin.vsto correctamente. ---> System.Net.WebException: No se puede encontrar una parte de la ruta de acceso 'C:\Users\Marc Rivero L%F3pez\Downloads\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin.vsto'. ---> System.Net.WebException: No se puede encontrar una parte de la ruta de acceso 'C:\Users\Marc Rivero L%F3pez\Downloads\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin.vsto'. ---> System.IO.DirectoryNotFoundException: No se puede encontrar una parte de la ruta de acceso 'C:\Users\Marc Rivero L%F3pez\Downloads\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin-BETA-38\OutlookPrivacyPlugin.vsto'.
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   en System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   en System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   en System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.FileWebRequest.GetResponse()
   en System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   en Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by Meddington** [comment]
I found a thread on the Microsoft forums with a work around if you have admin permissions. This is not something I can fix in the installer.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/c26d3f76-be37-4e1b-9d9a-84edae351e18/problem-with-vstoinstallerconfig
