### ISSUE TITLE
Attach public key with better/configurable name

### ISSUE THREAD

**Issue by Baebeca** [dejavusecurity/OutlookPrivacyPlugin#45]
Is there any solution to Change the default filename?
I think it is better to set the default filename to the corresponding email address.

peet@hello.com --> peet@hello.gpg

So the reciepient can handle better the public key.

thanks and best regards
Sebastian

**Comment by Baebeca** [comment]
in last branch is it still "public_key.pgp" :(

**Comment by Meddington** [comment]
due to filename character issues we will likely not use the email  address. Enigmail uses the keyid, but I don't think that's any better.

**Comment by Baebeca** [comment]
what Do think about a seeting fort this?
So Users can set a fix keyname or use tue defaultname?

**Comment by Reddi82** [comment]
you could replace characters dot to _, @ to _at_ and kill all other unusable chars, like this: my@example.com to my_at_example_com.pgp

Ist it possible, that the attached key is another as the exported public key from kleopatra?

**Comment by Baebeca** [comment]
I think a good idea is a configuration for User
A) static string as filename
B) emailaddress (specials chars replaced)
C) Keyid
D) Default

**Comment by Meddington** [comment]
BETA 54 will name using email address.

**Comment by Baebeca** [comment]
@Meddington sweeeeeett! :+1:

**Comment by Baebeca** [comment]
This doesnt work in my case - on every attached public key the filename is "public_key.asc"
I have no symbols in my email addrees - only letters
