### ISSUE TITLE
On having multiple IDs in one key

### ISSUE THREAD

**Issue by grssnbchr** [dejavusecurity/OutlookPrivacyPlugin#46]
More a question than an issue: 

I have a private/public-keypair that I use for my private email address (user@private.com).

In Kleopatra/pgp4win, I have added another user ID to this key, namely user@work.com, which is my work address.

The reason for this is that I want to use the same key for my work address.

Now, when I sign and encrypt an email from user@work.com in Outlook with the OutlookPrivacyPlugin, my friend receives it and it is correctly encrypted, but it shows to him that it is signed with user@private.com and not user@work.com. Therefore, he cannot send an encrypted reply to user@work.com, but only to user@private.com, which is not what I want. He somehow does not get the public key of user@work.com?! 

How can I configure OutlookPrivacyPlugin so that it signs it with user@work.com? 

Excuse my lack of general knowledge of PGP...

**Comment by Meddington** [comment]
Currently this plugin maps your account email to a pgp key. Currently there is not support for forcing the key to a specific one.

**Comment by cerkit** [comment]
I'm not sure if this is related, but I am attempting to send an email to the Adele test bot using the adele-en @ g n u . de address using the public key that it provided me. There are two emails in that key. I saved the public key to an .asc file and imported it into Kleopatra. After certifying and trusting both, I cannot send emails to them. When I go to send the encrypted email, I do not see either of them as available recipients.

**Comment by Meddington** [comment]
I believe this is a duplicate of issue #30.
