### ISSUE TITLE
Beta v38: Issue with UTF-/ISO-encoding of German Umlaute üöäß

### ISSUE THREAD

**Issue by mygithuber** [dejavusecurity/OutlookPrivacyPlugin#47]
Hello,
Outlook-2010-32bit/ Win7-64bit/Gpg4win-2.2.3 (gpg-only...):
If Outlook settings for outgoing mails are put to UTF-8, German Umlaute üöäÜÖÄß are correctly decoded on recipient's side.
If Outlook settings for outgoing mails are put to Westeuropäisch-ISO (pls refer to screenshot), German Umlaute üöäÜÖÄß are NOT properly decoded on recipient's side and signatures are broken.
Regards, mgh

![ol-iso](https://cloud.githubusercontent.com/assets/9347903/5536543/0302f4ec-8a94-11e4-9b78-cdd7bd137278.png)

**Comment by tx3eh8IUD1** [comment]
Why don't you just use UTF-8 then? That is what I do - seems to work flawless.

**Comment by mschnecke** [comment]
@tx3eh8IUD1 
"Westeuropäisch-ISO" is the standard coding setting in west european Outlook installation. So without changing this settings no one is really happy with this add-in and these settings are hard to find.

**Comment by tx3eh8IUD1** [comment]
I actually encountered a similar issue - if I get mails encrypted with K9 mail on Android and decrypt them in Outlook, the Umlaut ö, ä, ü and the letter ß also fail to decode properly. I don't think one can choose coding of K9 mails - any ideas? Is this something that could be countered through the plugin?

**Comment by Meddington** [comment]
Should be fixed for beta 42.
