### ISSUE TITLE
signature error if mail contains line >76 chars (sign only, no encryption)

### ISSUE THREAD

**Issue by cxagit** [dejavusecurity/OutlookPrivacyPlugin#51]
Only signing a message (no encryption) fails if a line >76 Chars is contained.

This seems to belong to this:
  
  RFC: Forming ASCII Armor: https://tools.ietf.org/html/rfc4880
  Note that some transport methods are sensitive to line length. While
  there is a limit of 76 characters for the Radix-64 data (Section
  6.3), there is no limit to the length of Armor Headers.

Other mail-clients (and plugins) are acting RFC conform and enforces a line break after each 76 chars during the signing. OPP doesn't do so.

Sent with OPP, 76 char line:
![image](https://cloud.githubusercontent.com/assets/9060772/5695371/df98e3ca-999f-11e4-9516-6e71125c506f.png)

Sent with OPP, 77 char line:
![image](https://cloud.githubusercontent.com/assets/9060772/5695382/9bdf6644-99a0-11e4-9178-8fcfb214aed1.png)

This is reproducible with Thunderbird+Enigmail, Outlook+OPP, AppleMail+GPGtools and Android+APG as receiver.

This doesn't occur when the mail is also encrypted, because then the signature will be applied over the encrypted data, where no line is longer than 76 chars.

**Comment by Meddington** [comment]
Fixed in next release. Have used same method as enigmail (prompt user with options)/.
