### ISSUE TITLE
Plugin ignores key Capabilities and Subkeys.

### ISSUE THREAD

**Issue by phryneas** [dejavusecurity/OutlookPrivacyPlugin#52]
Hi,
someone using OutlookPrivacyPlugin sent me a message.

Unfortunately, OPP seems to encrypt to the main key by default, ignoring key capabilities (and subkeys).

If you look at my key http://pgp.mit.edu/pks/lookup?op=vindex&search=0xD8C4AE56B76C94DD you will see, that the main key has only 'SC' capabilities, while one of the subkeys has 'E'.

Usually, messages to me should be encrypted using the latter, but apparently OPP seems to encrypt to the first (and seems not offer any choice, too).

Which leaves me with a message that can only be decrypted with a key protected by dragons, that is per default not on my PC ;)

If you need me for some testing, I'm available!

**Comment by Meddington** [comment]
I added some code to better deal with keys and subkeys and try to check the usage flags. I have not fully tested it, so may not work :)

**Comment by Meddington** [comment]
duplicate of #6
