### ISSUE TITLE
can't install because no valid certificate

### ISSUE THREAD

**Issue by Kenarso** [dejavusecurity/OutlookPrivacyPlugin#55]
System:
Windows 7 prfessional 64 Bit
Outllook 2013
I use the OutlookprivacyPlugin 38.
Now, I want upgrade to the version 40, but I get ever the same error.
Here you can see the orginal error:
------------------------------------------------

************** Ausnahmetext **************
System.Security.SecurityException: enutzerdefinierte Funktionen können in dieser Anwendung nicht verwendet werden, weil das Zertifikat, mit dem das Bereitstellungsmanifest für Outlook Privacy Plugin BETA signiert wurde, oder sein Speicherort nicht vertrauenswürdig sind. Wenden Sie sich an den Administrator, um weitere Unterstützung zu erhalten.
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
Die Zone der Assembly, bei der ein Fehler aufgetreten ist:
MyComputer
--------------------------------------------------

**Comment by Meddington** [comment]
See step 3 of the install instructions.

**Comment by Kenarso** [comment]
I followed these instaructions. 
When you have read my text correctly, you know that I use the version 38. Also I know the instruction.
Thx for your help

**Comment by Kenarso** [comment]
Sorry, I cant install the plugin. I have ever the same error. And I follow the installtation instruction. Also I follow the step 3!!!!
But I have the same error ever!
