### ISSUE TITLE
v.40: mails cannot be stored decrypted (permanently decrypt)

### ISSUE THREAD

**Issue by tx3eh8IUD1** [dejavusecurity/OutlookPrivacyPlugin#57]
I know issue #25 called for a fix - but users (including me) might want to store their e-mail unencrypted permanently. 

Could you please give us a choice in the settings? That would be wonderful.

Features like search do not work without permanent encryption. Also, if the user can read an e-mail (and thus trusts his system) - why not store it permanently?

EDIT: The safe button works after opening the e-mail.

**Comment by tx3eh8IUD1** [comment]
I just realized that you can click the safe button while opening the message.

An option would still be nice, though, so I don't have to click twice all the time for every received message (and sent message).

Also, it would be great if one could store unencrypted sent message copies locally (i.e. the email before it was encrypted).

**Comment by tx3eh8IUD1** [comment]
(somebody might want to make this a feature request and close the issue)

**Comment by Meddington** [comment]
Generally this will result in the email getting saved on the server. Normally a Bad Idea (tm).

**Comment by tx3eh8IUD1** [comment]
Meddington, this is not true when you use POP3.
