### ISSUE TITLE
Exception opening PGP MIME clear signed email

### ISSUE THREAD

**Issue by dimamizou** [dejavusecurity/OutlookPrivacyPlugin#58]
When I open a PGP MIME mail (with sigature.asc attachment) in Outlook Pro Plus 2013 (15.0.4569.1503) 32 bit OutlookPrivacyPlugin-BETA-40 crashes with message:

    http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102 property unknown or not found

**Comment by Meddington** [comment]
What mail client did you use to generate the inbound message with a sigature attachment?  Enigmail through my usage is not generating one and there is no crash.

**Comment by dimamizou** [comment]
I don't generate those mails, I receive them from diverse Mac/iPad users, so supposedly it is whatever client that is PGP capabale on these platforms... I'll start a survey on occation.

**Comment by Meddington** [comment]
Are the emails clear-text with only a signature?  If so I was able to get some samples using Apple Mail with GPGMail v2.1 plugin.

However, I am not getting this error, it's working okay. That property is should contain the email message body I need in order to verify the email signature.

If there is an email you could forward to me (meddington at gmail dot com) that would be helpful.

**Comment by dimamizou** [comment]
The mails were all multipart with HTML part and optional plain text. I have no sample at the moment, I shall ask my Mac-people if they can provide some for public use.
I forgot to mention 2 points:
1. All my incoming mails are mungled through Spamassassin at server, so the structure is not original anymore when they get to the plugin.
2. My Outlook is configured to show all mails as plain text per default. However, the crash happens  when I choose "Show as HTML" as well.

**Comment by Meddington** [comment]
Have you received other pgp/mime signed emails that do work?  Could you try sending yourself a PGP/Mime signed email from Thunderbird + Enigmail and see if the issue occurs?

I'll see if I can get spamassassin setup and tested.

**Comment by mygithuber** [comment]
Beta-46: Only signing with PGP/Mime is giving "** Invalid signature from "" with KeyId " at recipient's Outlook with OPP-b46.
NOT working, if sender is using PGP/Mime, with or without German Umlaute üöäß in message body. Recipient's Outlook shows message body with separate attachment.sig file.
Thunderbird/Enigmail or GPGrelay are working.
Regards!

**Comment by Meddington** [comment]
This is a duplicate of #34. Closing as such. Please use #34 for addition comments, updates, etc.
