### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by Vancore** [dejavusecurity/OutlookPrivacyPlugin#60]
Hi,

may I ask if you can you give me the information when you think (or expect) the plug-in will be fully released?

Thank you!

Greetings from Germany,
Marko

**Comment by BiberM** [comment]
Hi,

I would like to hook in. We would like to use this plugin as it is by far the most advanced open source GPG-Plugin for Outlook >= 2010. 
Currently one of the showstopper for us is the lack of support for html-emails.

Is there any plan when to release certain features or even a final version?

Best regards
Michael

**Comment by Meddington** [comment]
There is no current release timeline as this is a side project.  Sadly I'm not able to give enough time as it needs.  Happy to accept any code donations :)
