### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by Vancore** [dejavusecurity/OutlookPrivacyPlugin#65]
Hi Meddington,

sorry for asking a similar question, but can you tell me in which state this project currently is?

Is it a stable Plug-In or do you just need more time testing the Plug-In?

Thank you really much for the information!

Best regards,
Marko

**Comment by vollme-s** [comment]
Encryption Decryption and Signing works perfectly... from my Point there are only some beautifications to get it out of beta

**Comment by Meddington** [comment]
Definitely BETA.  There are a number of known issues that could cause it not to work for you, check out the bug list.  That said, I use it every day at work as do others.
