### ISSUE TITLE
BETA-40: Add-In menu gets invisble

### ISSUE THREAD

**Issue by vollme-s** [dejavusecurity/OutlookPrivacyPlugin#66]
The Add-In menu item gets invisible at restart of Outlook because mssphtb.dll seems to cause Outlook not working correctly.

activating the plugin dll fixes the Problem for the current session

**Comment by Meddington** [comment]
What version of outlook and operating system are you running? 64bit or 32bit office?  Does this happen every time you start outlook or does "restart" mean something specific?

**Comment by vollme-s** [comment]
win8.1 64bit Outlook2013.
and it happens every time i open outlook

**Comment by Meddington** [comment]
I'm using similar setup with no issues. What leads you to believe it's related to that search dll?

**Comment by vollme-s** [comment]
In the options page unser add ins, i open up the deactivated add ins from this plugin. There it says, that the dll got deactivated because outlook would not work correctly if it is activated. 
After activation and some "click around" the add in menu reappears.

**Comment by Meddington** [comment]
Strange, but I have been unable to reproduce so closing the issue.
