### ISSUE TITLE
Notify when updates are available

### ISSUE THREAD

**Issue by Baebeca** [dejavusecurity/OutlookPrivacyPlugin#67]
Integrate a Plugin-update Function.
I think a notification, that there is a newer version is available is fair enough

**Comment by Strykar** [comment]
This would be great!

**Comment by Meddington** [comment]
included in beta54

**Comment by Baebeca** [comment]
@Meddington 
Nice function! :-} I open my Outlook today, and i get a alert that there is a new version available.

Sweet ;)
