### ISSUE TITLE
Singing Issue of Installer

### ISSUE THREAD

**Issue by Fightbackman** [dejavusecurity/OutlookPrivacyPlugin#69]
German error Message of the .vsto file.

Short translation: The code signingn certifiacte isn't trusted.

"Benutzerdefinierte Funktionen können in dieser Anwendung nicht verwendet werden, weil das Zertifikat, mit dem das Bereitstellungsmanifest für Outlook Privacy Plugin BETA signiert wurde, oder sein Speicherort nicht vertrauenswürdig sind. Wenden Sie sich an den Administrator, um weitere Unterstützung zu erhalten."

After that i started the the setup.exe directly and get the same error.
Thies is the detailed eror report:

Name: Outlook Privacy Plugin BETA
Von: file:///C:/Users/Lukas/Desktop/OutlookPrivacyPlugin-BETA-40/OutlookPrivacyPlugin.vsto

************** Ausnahmetext **************
System.Security.SecurityException: enutzerdefinierte Funktionen können in dieser Anwendung nicht verwendet werden, weil das Zertifikat, mit dem das Bereitstellungsmanifest für Outlook Privacy Plugin BETA signiert wurde, oder sein Speicherort nicht vertrauenswürdig sind. Wenden Sie sich an den Administrator, um weitere Unterstützung zu erhalten.
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustPromptKeyInternal(ClickOnceTrustPromptKeyValue promptKeyValue, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInTrustEvaluator.VerifyTrustUsingPromptKey(Uri manifest, DeploymentSignatureInformation signatureInformation, String productName, TrustStatus status)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.ProcessSHA2Manifest(ActivationContext context, DeploymentSignatureInformation signatureInformation, PermissionSet permissionsRequested, Uri manifest, ManifestSignatureInformationCollection signatures, AddInInstallationStatus installState, TrustStatus sha256TrustStatus, X509Certificate2 sha256PublisherCert)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySecurity(ActivationContext context, Uri manifest, AddInInstallationStatus installState)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
Die Zone der Assembly, bei der ein Fehler aufgetreten ist:
MyComputer

**Comment by ttrueten** [comment]
The error can be reproduced with me. I just can use Beta 35. ...

**Comment by ttrueten** [comment]
Solved!  Source Drive must be a local Drive, not Network...

**Comment by Fightbackman** [comment]
Used local drive, was no difference

**Comment by ttrueten** [comment]
Did you unlock the zip File?

**Comment by Baebeca** [comment]
is there no solution with the "unlock" Problem?
Sorry - but I doesnt develop for Windows - so i dont know

**Comment by Meddington** [comment]
Combining this into #77 which is a fuller solution.

However to work around typically you will:

1. Unblock zip
2. Install from local drive
3. On Windows 8.1 you may need to add the certificate to your trust store during installation
