### ISSUE TITLE
Encryption fails w/o error and even though "Encrypt" is highlighted

### ISSUE THREAD

**Issue by tx3eh8IUD1** [dejavusecurity/OutlookPrivacyPlugin#70]
I have a rather serious issue:

When I try to send an encrypted e-mail with the wrong sending address (i.e. the "From" field in Outlook), I get the following error message:

String reference not set to an instance of a String. 
Parameter name: s 

see: 
![outlookprivacy1](https://cloud.githubusercontent.com/assets/6958661/7243450/2977ae1a-e79b-11e4-9662-af9935d0cec7.png)

Naturally, everyone just clicks "OK". I then realize, even without the help of the meaningless warning message, that I had chosen the wrong "From" sending address.

Now, when I hit CTRL+ENTER to send, the message goes through without warning (as expected, since I corrected the "From" field and I am now using an account which is setup with Kleopatra). However, if I haven't put in my password anytime recently, it will also go without encryption (because no password prompt shows).

It works the other way as well: once the error message came up, even though the "Encrypt" field is still highlighted, when I change to a sender in the FROM field that has no key pair, it will also send the email unencrypted. I think the program should "uncheck" the "Encrypt" field or provide another error message. Ideally, it would encrypt the e-mail if an appropriate sender is selected without any further hassle.

This is what I mean by highlighted "Encrypt":
![outlookprivacy2](https://cloud.githubusercontent.com/assets/6958661/7243589/e480a9fe-e79c-11e4-83b1-8b739d5ec52a.jpg)

**Comment by Meddington** [comment]
How are you showing the from field? I have to switch profiles to get a different from field in my configuration.

The message about "s" is an error about retrieving the error message text.  Haven't been able to reproduce that.

The core issue might should be resolved now, as I've fixed several issues related to the sign/encrypt buttons.

**Comment by tx3eh8IUD1** [comment]
The issue is indeed fixed. The "s" fault also does not appear any longer.

I am now running Outlook from Office Pro Plus 2013 on Win 10.
See attached for the two correct errors that I now receive - if I switch the "From" field (also shown in pictures!) the plugin correctly asks for my key and encrypts the message afterwards.

Very good work! Thank you for the fix & the plugin!

![outlook-privacy1](https://cloud.githubusercontent.com/assets/6958661/9027754/581edd38-3962-11e5-8857-d0f6ad32a848.png)
![outlook-privacy2](https://cloud.githubusercontent.com/assets/6958661/9027755/5822b7c8-3962-11e5-8e69-8e6ad15dd1d3.png)
![outlook-privacy3](https://cloud.githubusercontent.com/assets/6958661/9027756/5827c6a0-3962-11e5-8e7f-a5b0ecef3f1c.png)
