### ISSUE TITLE
Decrypting PGP-MIME message in UTF-8 displays with incorrect encoding

### ISSUE THREAD

**Issue by asharayev** [dejavusecurity/OutlookPrivacyPlugin#73]
I have installed version v1.0.0.64 of the plugin and tried to open an encrypted e-mail that was sent using Mozilla Thunderbird client with PGP encoding.
The plugin has decrypted the e-mail, but all non-us characters (in our case - russian characters) are displayed using "unknown" utf symbor (?).

![image](https://cloud.githubusercontent.com/assets/7449365/7562949/6c98a946-f7e1-11e4-8bf8-5a02bd62e681.png)

The original "encrypted.asc" part contained the following (decrypted using pgp command-line tools):
```
Content-Type: multipart/mixed; boundary="A5POk63jeNeLf7AccOfBTqWtLPOnB5u8T"

--A5POk63jeNeLf7AccOfBTqWtLPOnB5u8T
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable


=D0=97=D0=B0=D1=88=D0=B8=D1=84=D1=80=D0=BE=D0=B2=D0=B0=D0=BD=D0=BD=D0=BE=D0=
=B5 =D0=B8 =D0=BF=D0=BE=D0=B4=D0=BF=D0=B8=D1=81=D0=B0=D0=BD=D0=BD=D0=BE=D0=
=B5

On 05/11/2015 11:44 AM, Alexey Sharayev wrote:
> =D0=95=D1=89=D0=B5 =D0=BE=D0=B4=D0=B8=D0=BD =D1=82=D0=B5=D1=81=D1=82
> =20

>=20
>=20

--A5POk63jeNeLf7AccOfBTqWtLPOnB5u8T--
```
The codes correctly correspond to russian UTF-8 characters (D097 => letter З, etc.)
The first line in the e-mail should read as "Зашифрованное и подписанное".

**Comment by asharayev** [comment]
The problem is that SharpMimeTools does not correctly parse such unicode parts.
See OutlookPrivacyPlugin.cs, line 735 inside HandlePgpMime() method:
```
			SharpMessage msg = new SharpMessage(cleartext);
			string body = mailItem.Body;
```
I see that SharpMimeTools is only used within HandlePgpMime and probably can be replaced with another solution that correctly supports unicode, e.g. I've tested it with MimeKit library (see 
https://github.com/jstedfast/MimeKit)

Getting HTML/plain text is pretty simple:
```
		    MimeMessage mimeMessage = MimeMessage.Load(new MemoryStream(this._encoding.GetBytes(cleartext)));
			string body = mimeMessage.HtmlBody ?? mimeMessage.TextBody;
```
as well as getting attachments that might be inside the encrypted file:
```
			foreach (MimePart mimeAttachment in mimeMessage.Attachments.Where(x => !string.IsNullOrEmpty(x.FileName))
                                                .Union(mimeMessage.BodyParts.Where(x => !string.IsNullOrEmpty(x.FileName))))
			{
				var fileName = mimeAttachment.FileName;
				var tempFile = Path.Combine(Path.GetTempPath(), fileName);

				using (FileStream fout = File.OpenWrite(tempFile))
				{
					mimeAttachment.ContentObject.DecodeTo(fout);
				}

				mailItem.Attachments.Add(tempFile, Outlook.OlAttachmentType.olByValue, 1, fileName);
			}
```

**Comment by asharayev** [comment]
Sorry, the close above was incorrect. reopened.

**Comment by Meddington** [comment]
Fixed in next release.
