### ISSUE TITLE
Deploy using msi installer to prevent certificate issues

### ISSUE THREAD

**Issue by Meddington** [dejavusecurity/OutlookPrivacyPlugin#77]
The certificate issues are a larger pain on Windows 8.1 machines. Using a regular msi installer instead of a one-click installer should fix the issue.

https://msdn.microsoft.com/en-us/library/cc442767.aspx

**Comment by Meddington** [comment]
Done, will be included in next release

**Comment by Baebeca** [comment]
I cant upgrade with the new exe file, a manual deinstall of old version is needed.
After Manual remove the old Version, Installation works fine

---------------
Name: 
Von: file:///C:/Program Files (x86)/Outlook Privacy Plugin/OutlookPrivacyPlugin.vsto

************** Ausnahmetext **************
Microsoft.VisualStudio.Tools.Applications.Deployment.AddInAlreadyInstalledException: Die Anpassung kann nicht installiert werden, weil derzeit eine andere Version installiert ist und von diesem Speicherort nicht aktualisiert werden kann. Zum Installieren dieser Anpassungsversion müssen Sie folgendes Programm zuerst über "Software" deinstallieren: Outlook Privacy Plugin BETA. Installieren Sie anschließend die neue Anpassung von folgendem Speicherort: file:///C:/Program Files (x86)/Outlook Privacy Plugin/OutlookPrivacyPlugin.vsto
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.VerifySolutionCodebaseIsUnchanged(Uri uri, String subscriptionId, Boolean previouslyInstalled)
   bei Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()
-----------------
