### ISSUE TITLE
automaticly encrypted beforde send - when receiver have no key

### ISSUE THREAD

**Issue by Reddi82** [dejavusecurity/OutlookPrivacyPlugin#78]
I would set the settings to automaticly send encrypted eMails. This option was the reason for this plugin. But when the receiver hasn't a public key, I'll get an error message and have to select an key. I understand the reason, because I have studied safety with RSA, AES, ... 

By this error message you must could select the option: "Send email without encryption". 

Otherwise you must cancel action, disable encryption end retry...

Best regards

**Comment by Baebeca** [comment]
+1
But i wish me in this Szenario a automatic lookup for the needed public key on public keyserver, if i have it not local in my store

So The Plugin can check for new keys, and i will be notified and can make a Manual Import in my list

**Comment by Meddington** [comment]
Fixed in beta 41.
