### ISSUE TITLE
Plugin causing Exchange account lockouts

### ISSUE THREAD

**Issue by andrewgdotcom** [dejavusecurity/OutlookPrivacyPlugin#82]
Whenever I have the privacy plugin enabled on my Outlook (2010, but ISTR I also had the problem in 2013), within a few minutes I start getting prompted for my exchange password. This never works, because by this point my domain account is locked out due to excessive password failures (the existing connection continues to work so long as it is active). The laptop I am using is not in the domain. This happens even if I have not changed my domain password in some time.

**Comment by Meddington** [comment]
I've looked through the code a couple times and can't see any reason this would/could happen.  We don't make any quests for data outside of the current mail item. We only activate when an email is actually opened (e.g. no preview pane). And by default will avoid saving out data.

I'll see if I can get 2010 installed, I'm using 2013 on an exchange server.

**Comment by andrewgdotcom** [comment]
FYI this hasn't reoccurred yet with the latest build, so it may be fixed...

**Comment by Meddington** [comment]
Thanks for the update.  This is a strange issue and I'm not sure why it would be resolved in the latest builds. I'm going to close the issue for now. If it happens again add a comment and I'll re-open.
