### ISSUE TITLE
File Type 

### ISSUE THREAD

**Issue by lukasroemer** [dejavusecurity/OutlookPrivacyPlugin#83]
Hey there! I'm using the plugin to securely communicate with an orginization. They use PGP decryption for their whole company, such that encrypted Mails get decrypted automatically and then sent to their Exchange server. The Exchange server only accepts certain file types and clients from the organization do not receive any encrypted attachements of mine due to this restriction. Their exchange server reports that it receives attachements with the name "email" withouth any suffix and therefore does not accept the attachement.

In my view this might be a problem with their decryption software, or does the plugin actually convert files to other types than .pgp?

**Comment by Meddington** [comment]
The only change to the attachment name made it to append a .pgp to the file name.  You can check this by looking at your sent email list.
