### ISSUE TITLE
Symantec Endpoint Protection false-positive

### ISSUE THREAD

**Issue by TheFiZi** [dejavusecurity/OutlookPrivacyPlugin#85]
Installed the latest BETA46 and my Symantec Endpoint Protection wasn't a fan:

	Scan type: Auto-Protect Scan
	Event: Security Risk Found!
	Security risk detected: Manually Generated Anomaly
	File: c:\users\<USERNAME>\appdata\local\assembly\dl3\wynzmy4w.118\ljhlqrd8.tmj\57b2b9e3\00a0340b_4a9ad001\outlookprivacyplugin.dll
	Location: Deleted or access blocked
	Computer: 305-132-01B
	User: <USERNAME>
	Action taken: Clean succeeded
	Date found: June-11-15  9:59:38 AM

Not sure if there is much that can be done but figured I should report it.

Most Enterprise users can't configure exceptions in their endpoint antivirus. I'm one of them so unfortunately I cannot white list this DLL and because Symantec quarantined it the add-on doesn't work.

**Comment by Meddington** [comment]
Thanks for reporting this. Symantec has a site to report false positives.  Please go ahead and report the false positive.

https://submit.symantec.com/false_positive/

**Comment by TheFiZi** [comment]
I've submitted the information to Symantec

**Comment by TheFiZi** [comment]
Sorry for the delay. Was on vacation. Good news!

	From: falsepositives@symantec.com [mailto:falsepositives@symantec.com] 
	Sent: 2015-06-16 00:44
	To: 
	Subject: [No Reply] False Positive submission (3802419)

	In relation to submission [3802419].

	Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

		7CF70651C5B44A65F97D8A69D32C69EB - OutlookPrivacyPlugin-BETA-46-Setup.exe
		9109606E14B8CBD717120FE2D2D68919 - OutlookPrivacyPlugin.DLL


	The updated detection(s) will be distributed in the next set of virus definitions, available via LiveUpdate or from our website at http://securityresponse.symantec.com/avcenter/defs.download.html

	Please note that whitelisting can take up to 24 hours to take effect.

	Decisions made by Symantec are subject to change if alterations to the Software are made over time or as classification criteria and/or the policy employed by Symantec changes over time to address the evolving landscape.

	If you are a software vendor, why not take part in our whitelisting program?
	To participate in this program, please complete the following form: https://submit.symantec.com/whitelist
