### ISSUE TITLE
OPP -> Enigmail -> OPP: Unable to decrypt final message

### ISSUE THREAD

**Issue by meveric** [dejavusecurity/OutlookPrivacyPlugin#86]
If you send a reply or forward a message to a user with current v1 Beta 46 plugin the Mail can not be opened in Outlook 2010. It's just shown blank.

But if you simply change the Subject and remove "Re, Fwd, FW", etc. it's working again.

**Comment by Meddington** [comment]
Just to clarify you are replying to an email which is then sent to another user with Outlook 2010 and the email cannot be opened?

**Comment by meveric** [comment]
Actually it's between Outlook and Thunderbird with Enigmail Plugin.

Thunderbird -> Outlook working
Outlook -> Thunderbird working
Thunderbird -> Outlook -> Thunderbird working
Outlook -> Thunderbird -> Outlook NOT working

If i remove the "Re:" in front of the Mail the reply from Thunderbird back to Outlook is working.
Same goes for Fwd: Mails can not be displayed in Outlook, but when "Fwd:" is removed from the Subject it's working.

**Comment by Meddington** [comment]
In the outlook -> tb -> outlook, does the content start with "> " prefixes on each line (e.g. reply/forward), or is it a regular message?

**Comment by Meddington** [comment]
Testing with the latest version I can't get this to trigger.  Also, we are not checking the subject line at all, so I'm not sure why changing it would affect anything, unless is causes some change in behavour in TB.

**Comment by meveric** [comment]
Retesting with v1 BETA-49 was successful.
Means the bug seems to be fixed in the newer version.

Thanks :+1:
