### ISSUE TITLE
Outlook 2013 preview Window

### ISSUE THREAD

**Issue by Baebeca** [dejavusecurity/OutlookPrivacyPlugin#87]
The Preview Windows in Outlook 2013 x64 does not work.
See attached Screenshots.
If i doublecklick the email, to open the Content in a new Windows it works and both mails are shown as plain

![encrypt_email](https://cloud.githubusercontent.com/assets/6824545/8288081/1a2b27a2-1914-11e5-95f3-86ee52fd3245.png)
![fb_mail](https://cloud.githubusercontent.com/assets/6824545/8288082/1a2c2058-1914-11e5-9a23-03692d1050c9.png)

**Comment by Meddington** [comment]
duplicate of #63.  OPP currently does not support the preview pane.
