### ISSUE TITLE
Moving messages between IMAP folders with Outlook corrupts signatures

### ISSUE THREAD

**Issue by docmalloc** [dejavusecurity/OutlookPrivacyPlugin#88]
I am testing interoperability between different mailers atm:

Sender: Thunderbird or Evolution
Receiver: Outlook 2013 with OutlookPrivacyPlugin Build 5627
Message: OpenPGP PGP/MIME signed message

Problem: 
When I move a message to a different IMAP folder with outlook, signature check fails in clients different to Outlook

When I receive the mail with IMAP and open the mail in Outlook, Thunderbird or Evolution: signature check is successful

In the next step, I move the mail to a different IMAP folder:

Outlook: signature check is successful
Thunderbird and Evolution: signature check is fails

I checked the differences between message source code of the original message and the modified, and Outlook seems to do major rewrites. I reverted the changes and in may case, the line breaks in the message body "Content-Type" header made verification fail:

Thunderbird and Evolution fail with:

Content-Type: text/plain;
	charset="utf-8"

Thunderbird and Evolution pass with:

Content-Type: text/plain; charset="utf-8"

**Comment by Meddington** [comment]
Could you try this with OPP disabled? I'm guessing this is just an outlook issue and not related to the plugin. The plugin shouldn't be modifying the mail message at all.

**Comment by Meddington** [comment]
I've reproduced this in my test environment with OPP disabled. This appears to be an outlook related issue and not something occurring due to OPP.

**Comment by docmalloc** [comment]
THX for your efforts!
