### ISSUE TITLE
Verify and/or decrypt available from preview pane causing issues

### ISSUE THREAD

**Issue by docmalloc** [dejavusecurity/OutlookPrivacyPlugin#89]
Receiver: Outlook 2013 with OutlookPrivacyPlugin Build 5627
Message: OpenPGP Inline PGP signed message

With a  Inline PGP signed message stored in an IMAP folder, the signature is not checked automatically.

When using the preview pane and pressing "verify" , the result of the verification is stored permanently in the message body, even multiple times:

** Valid signature from "user <user@xyz>" with KeyId 
xxx.

** Valid signature from "user <user@xyz>" with KeyId 
xxx.

When opening the message and pressing "verify" and closing the message, Outlook asks me if I want to save the changes.

**Comment by Meddington** [comment]
Currently OPP doesn't support the preview pane (see #63). The actual bug here is we should be blocking verify/decrypt on preview pane until it's supported.
