### ISSUE TITLE
Moving encrypted PGP/MIME messages to different IMAP folder in Outlook corrupts message

### ISSUE THREAD

**Issue by docmalloc** [dejavusecurity/OutlookPrivacyPlugin#90]
When moving an encrypted or encrypted and signed PGP/MIME  message to a different IMAP folders, the message is corrupted afterward and other mail applications fail to open the encrypted message:

Outlook 2013 + Plugin Build 5627
Original message content: loret ipsum

**Thunderbird 31.7.0 on GNU/Linux:**
Can decrypt but additional text is shown:
Content-Type: multipart/mixed; boundary="hXk1bveRgEMgMlBMrskGTqh8OwmnlAF72"

--hXk1bveRgEMgMlBMrskGTqh8OwmnlAF72
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

loret ipsum

--hXk1bveRgEMgMlBMrskGTqh8OwmnlAF72--

**Thunderbird 38.0.1 on Windows**
No text shown, only attachments provided:
- PGP_MIME version identification.dat
- encrypted.asc

**Evolution 3.16 on GNU/Linux**
No text shown, only attachments provided:
- unknown attachment (PGP_MIME version identification.dat)
- PGP/MIME-encrypted message header attachment (encrypted.asc)

**Claws 3.11.1**
Show following message content:

X-Mailer: Microsoft Outlook 15.0

[PGP_MIME version identification.dat  application/pgp-encrypted (11 bytes)] 

[encrypted.asc  application/octet-stream (1119 bytes)]

**Comment by Meddington** [comment]
This seems like a duplicate of #88.  Again, I don't think this is related at all to this plugin, I'm guessing this is an outlook issue. Could you please try it with OPP disabled to verify?

**Comment by Meddington** [comment]
I've reproduced this in my test environment with OPP disabled. This appears to be an outlook related issue and not something occurring due to OPP.

**Comment by docmalloc** [comment]
THX for your efforts!
