### ISSUE TITLE
Wrap Lines Popup?

### ISSUE THREAD

**Issue by Baebeca** [dejavusecurity/OutlookPrivacyPlugin#92]
Since last update i get sometimes the following popup if i have copy (STRG+V) to my email content.
If i set automatic Line breaks, every break is duplicatet - so the content looks very strange ;)

Is this an issue or a misstake by me?

![wrap_lines](https://cloud.githubusercontent.com/assets/6824545/8395856/1bb1bbca-1d8a-11e5-8691-34dca407d43e.png)

**Comment by Meddington** [comment]
There is a line length limitation defined in the OpenPGP standard. If the line length is longer than 72 characters it must be wrapped. This specific dialog is new in response to a bug logged that we did not detect and warn the user.

The dialog is similar to the enigmail plugin for thunderbird.

**Comment by Baebeca** [comment]
Yes, but why all lines get an extra wrap?
It is possible to only wrap lines with more than 72 chars?

**Comment by Baebeca** [comment]
A other nice way is to dipslay in the popup the Content of the incorrect line.
At this Moment i have this popup in a big email, but i cant find the long line
After some searching it was a very long line in the signature of the email Partner in the bottom

**Comment by Meddington** [comment]
Only lines that are too long will be wrapped automatically.

**Comment by Baebeca** [comment]
@Meddington 
I will 2 Screenshots. One of the orig mail, and one of the mail after sign ans send

Here you can see, that every line are wraped 2 times

![line_wrap_wrapped](https://cloud.githubusercontent.com/assets/6824545/8552846/eed3fd86-24df-11e5-8c86-167a3c7cf6ca.png)
![line_wrap_orig](https://cloud.githubusercontent.com/assets/6824545/8552847/eed6093c-24df-11e5-93dd-5f37319f9fcd.png)

**Comment by Meddington** [comment]
Ah I see. I'll push a new build later today with the fix.

**Comment by Baebeca** [comment]
@Meddington do you already had time to create the new build?
No stress - i will wait if you have enough time to create it

thansk so far!

**Comment by Meddington** [comment]
Sorry I forgot to upload it!  It's up now.

**Comment by Baebeca** [comment]
@Meddington 
Great Work - it works fine now!

Closed
