### ISSUE TITLE
"Item has already been added." OL2013

### ISSUE THREAD

**Issue by Dyddye** [dejavusecurity/OutlookPrivacyPlugin#93]
# Setup
* Windows 7 Pro 64bit
* Outlook 2013 32bit
* GPG4WIN: 2.2.4
* OPP: v1 BETA-46

# Steps:
1. new mail
2. add receiver (public-key in Kleopatra), header, content
3. click 'encrypt'
4. click 'send'

# Result:
Pop-Up showing:
**Outlook Privacy Error**
> Item has already been added. Key in dictionary: '-7207277542740830841'
>  Key being added: '-7207277542740830841'

# Expected
1. encrypt mail
2. send mail

**Comment by Meddington** [comment]
I'm adding some code to include additional information in the error popup. Try out beta 39 and let me know if the issue reproduces.

**Comment by Meddington** [comment]
Unable to reproduce this issue, so closing.
