### ISSUE TITLE
Error message "the type serialized in the .resources file..."

### ISSUE THREAD

**Issue by ZEROF** [dejavusecurity/OutlookPrivacyPlugin#94]
Hi,

I try to use plugin with Office 2010. Plugin installation is ok and settings looks good too.

1. Wrong plugin path (maybe). 

http://s30.postimg.org/q4feshk6p/pgp.png

2. I get this error when i try to send mail:

http://s30.postimg.org/z0q6wfasx/pgp_shit.png

Any idea how to fix this?

Thanks

**Comment by ZEROF** [comment]
FIX: Install .NET Framework 4.5, didn't work with version 4.

Done!

**Comment by Meddington** [comment]
There is also a patch for v4 of the .NET framework. 

https://support.microsoft.com/en-us/kb/2538717
