### ISSUE TITLE
outlook encrypt error

### ISSUE THREAD

**Issue by fogeater** [dejavusecurity/OutlookPrivacyPlugin#96]
win7 32, pgp4win 2.2.5, outlook 2010 32

when I chose encrypt, it says 

.resources error
It should be system.windows.forms.listviewitem but it is system.windows.forms.listviewitem + listviewsubitem.

**Comment by Meddington** [comment]
Please post a screen shot of the error.

**Comment by Meddington** [comment]
duplicate of #94.
